=encoding UTF-8

=head1 NAME

Lingua::Segment::TH - Thai word segmenter

=head1 VERSION

This document describes Lingua::Segment::TH v0.01.

=head1 SYNOPSIS

    use Lingua::Segment::TH qw( segment_th );

    # 'กกต', 'ศรรม', 'ขจ'
    @words = segment_th('กกตศรรมขจ');

=head1 DESCRIPTION

...

=head1 SEE ALSO

=over

=item * L<thailang4r|https://github.com/veer66/thailang4r>

=item * L<ThaiWordseg|http://thaiwordseg.sourceforge.net/>

=item * L<libthai|http://linux.thai.net/projects/libthai>

=item * L<Lingua::TH::Segmentation>

=back

=head1 AUTHOR

Nick Patch <patch@cpan.org>

=head1 COPYRIGHT AND LICENSE

© 2013 Nick Patch

This library is free software; you can redistribute it and/or modify it under
the same terms as Perl itself.
