=encoding UTF-8

=head1 NAME

Lingua::Segment::TH - Thai word segmenter

=head1 VERSION

This document describes Lingua::Segment::TH v0.01.

=head1 SYNOPSIS

    use Lingua::Segment::TH qw( segment_th );

    @words = segment_th($phrase);

=head1 DESCRIPTION

This module provides word segmentation (also known as word breaking) for the
Thai language.  The C<segement> and C<segment_th> functions are synonymous and
can optionally be exported.  They accept a string of Thai text and return a list
of words.

=head1 SEE ALSO

=over

=item * L<thailang4r|https://github.com/veer66/thailang4r> for Ruby

=item * L<PhlongTaIam|https://github.com/veer66/PhlongTaIam> for PHP

=item * L<ThaiWordseg|http://thaiwordseg.sourceforge.net/> for C

=item * L<libthai|http://linux.thai.net/projects/libthai> for C

=item * L<Lingua::TH::Segmentation> for Perl (interface to ThaiWordseg)

=back

=head1 ACKNOWLEDGEMENTS

This module is based on the Ruby library
L<thailang4r|https://github.com/veer66/thailang4r> by
L<Vee Satayamas|https://github.com/veer66>, who also authored ThaiWordseg.

This module is brought to you by L<Shutterstock|http://www.shutterstock.com/>.
Additional open source projects from Shutterstock can be found at
L<code.shutterstock.com|http://code.shutterstock.com/>.

=head1 AUTHOR

Nick Patch <patch@cpan.org>

=head1 COPYRIGHT AND LICENSE

© 2013 Nick Patch

This library is free software; you can redistribute it and/or modify it under
the same terms as Perl itself.
